version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    ports:
      - "5434:5432"

    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
